name: pinch_zoom_image_example
description: Demonstrates how to use the pinch_zoom_image plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pinch_zoom_image:
    path: ../
  cached_network_image: "^0.4.2"

flutter:
  uses-material-design: true
  assets:
   - images/camel.jpg
